# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fe733a61f18a94fd8fac3cacfc26d115517cad496f72c99f74b89de1110399a798d633ae0fa50fedfd0d07db18054565d0ad30f6bef79096ea6e68cc3fe964b

test:
  secret_key_base: adbfe74993a24512e116a0c29d58e1aa0d9a7cdfe913e6d28a71c2ed648201236f12eec2a192e6073478ce3aedae41b1433378a52411c557847d5bc9955ee1ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
